default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10

development:
  <<: *default
  database: photobooth_development
  username: <%= ENV["DB_USERNAME"] || 'photobooth' %>
  password: <%= ENV["DB_PASSWORD"] || 'photobooth' %>

test:
  <<: *default
  database: photobooth_test
  username: <%= ENV["DB_USERNAME"] || 'photobooth' %>
  password: <%= ENV["DB_PASSWORD"] || 'photobooth' %>

production:
  <<: *default
  database: photobooth
  pool: 20
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
