development: &development
  adapter: postgresql
  encoding: unicode
  database: photobooth_development
  pool: 20
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>

test:
  <<: *development
  database: photobooth_test